// src/locales/en/About.svelte
<h2>THE MOVIE SHRINK</h2>
<h3 style="margin-left: 10px;">
  <em>- Understanding significant films</em>
</h3>
<p>
  <em>The Movie Shrink</em> is a cinema commentary site that focuses on films that
  have something particularly meaningful to say to us about our contemporary world
  and the societies within it.
</p>
<p>
  Concentrating on a few dozen carefully chosen films a year from all over the
  planet, two each month, the site begins by offering an informed analysis and
  interpretation of what these significant films tell us about what it is to be
  living in our times.
</p>
<p>
  The approach taken to better understand these significant films is based on
  the tradition of
  <a href="/en/hermeneutics">hermeneutics</a>.
</p>
<p>
  Stated broadly,
  <a href="/en/hermeneutics">hermeneutics</a> concerns the art and method of
  interpretation. It has of course many dimensions and applications. Its
  application to films is part of the larger tradition of applying
  <a href="/en/hermeneutics">hermeneutics</a> to artistic creations. Seen in this light,
  art is not only a question of aesthetics, but it participates in the search for
  knowledge. More specifically, in our case, knowledge about society and its many
  contemporary dimensions.
</p>

<h3>MORE ABOUT US</h3>
<p>
  After viewing certain films, we often are left with some questions and the
  feeling that there was more to the story than its script told us: was there a
  lesson to be learned; what did the film director want to tell us, or is that
  relevant; or, was there no message or meaning at all?
</p>
<p>
  Sometimes we would like to share those questions and our understanding of the
  film with those of others. Alas, more often than not, our friends, family, or
  colleagues have not viewed that specific film, and have seen other films that
  we, ourselves, have not seen. Film critics will often judge the artistic
  merits of the movie, and give it a comparative ranking, sometimes recommending
  it, but that does not always enlighten us with a fuller understanding of the
  film we have seen.
</p>
<p>So, with whom should we compare notes?</p>
<p>
  <em>The Movie Shrink</em> constitutes a partial but specific answer to these questions.
  It is a meeting place, a forum for initiating a conversation, a dialogue for the
  understanding of particularly significant and complex films of the world.
</p>
<p>
  All conversation or dialogue must begin with a specific statement.
  <em>The Movie Shrink</em> thus begins, in this site, with an opening statement
  on a particular film, in the form of a specific understanding and interpretation
  of the film that is under scrutiny. It gets, as it were, the ball rolling.
</p>
<p>
  Once an interpretation has been offered on this site, readers can join the
  conversation at <b>The Movie Shrink's Forum</b>, to read comments coming from
  others who have viewed that film, and eventually participate in the exchanges
  by offering an understanding or interpretations of their own. Of course,
  viewers that want to view a film from scratch, without being influenced by the
  interpretation and understanding offered on this site, could read our comments
  only after having viewed the movie. In our capsules analyzing specific films,
  there are, to this end, spoiler alerts to remind the reader.
</p>
<p>
  In offering a specific interpretation for a film, to get the ball rolling, as
  suggested earlier, we need some guidelines that are explicit and methodical,
  yet flexible enough to adapt to the understanding of the specific film under
  study. With these guidelines, we try to avoid the risk that our analysis,
  understanding, and interpretation become only wild speculation or a uniquely
  personal view of the film that has been viewed.
</p>
<p>
  And so, the next question becomes: is there a discipline, a tradition of
  sorts, that helps us navigate towards a better understanding of the film under
  scrutiny? We believe to have found such explicit yet flexible guidelines in
  the tradition of
  <a href="/en/hermeneutics">hermeneutics</a>, as suggested at the outset.
</p>
<p>
  <em>The Movie Shrink</em> proposes to begin the exchanges by using the
  <a href="/en/hermeneutics">hermeneutic</a> approach, applied to films, to reach a
  better understanding of what can be considered as the larger story behind the
  specific and more limited story in the film. More can be read on
  <a href="/en/hermeneutics">hermeneutics</a> by going to
  <a href="/en/hermeneutics">hermeneutics</a> on this site.
</p>
<p>
  The underlying assumption of this site, as stated earlier, is that art and
  films, in particular, say a lot about where we are, today, in the human story.
  They can be seen, indeed, as chapters in the human story.
</p>
<p>
  <a href="/en/hermeneutics">Hermeneutics</a> is involved in the search for
  understanding when a work of art (in our case, a film) tells us something
  about where we are today, collectively, but says it in an indirect and
  understated way. The object of this site is to follow this
  <a href="/en/hermeneutics">hermeneutic</a> road to understand films that present some
  intriguing and challenging elements which demand interpretation for a fuller understanding.
  The 1653 painting of Rembrandt, “Aristotle contemplating a bust of Homer”, represents
  a visual model of what we want to achieve in this site: the poet (Homer or, in
  our case, the filmmaker) tells a story, but the philosopher (Aristotle or, in our
  case the interpreter or analyst of the film) offers an understanding that may go
  beyond the story that is told in the film and beyond the intentions of the creator
  (or the filmmaker).
</p>
<p>
  This site is not about the aesthetics of a film or its artistic merit. Again,
  taking Rembrandt’s painting as an example and inspiration (see the painting
  shown on this site), Aristotle is not presumed to comment critically on
  Homer’s style of writing. In keeping with this spirit, not once will we
  comment on the artistic or creative aspects of a film (its photography or
  acting for example). This is why this site is definitely not film criticism.
</p>

<h3>ABOUT JEAN-CHARLES MERCIER</h3>
<p>
  Jean-Charles Mercier (a.k.a. Jean Mercier) is a professor of political science
  at Université Laval in Québec City, Canada, where he taught for several
  decades on politics,
  <a href="https://en.wikipedia.org/wiki/Institutional_economics"
    >institutional economics</a
  >, environmental policies, and interpretative methods. He started writing on
  cinema in different Canadian reviews in the 1990’s. More is available on his
  overall activities at jean-mercier.com
</p>
<h3>WHAT THIS FILM SITE IS NOT</h3>
<p>
  Before going further in describing what this site,
  <em>The Movie Shrink</em>, is about, let us say a few words about what it is
  not.
</p>
<p>
  Although the title of our film site could suggest that we are looking at the
  artist’s psychological makeup, <em>The Movie Shrink</em> is not about individual
  psychology at all, but about collective and social elements that are present in
  specific significant films. It is not, consequently, about the inner-world or intention
  of the author, screenwriter, filmmaker, or director. There is indeed no search
  about the intentions of the artist, of the writer, or the creator. We are interested
  in the outcome, the film itself, and believe that the film has a meaning beyond
  its creator, as the artists are not necessarily conscious of the richness of their
  creation. We are, on the other hand, very much interested in the opinion of the
  artist or filmmaker concerning his creation, but we are not tied by it. In this
  spirit, we want to draw, again, the reader’s attention to Rembrandts’ painting
  of 1653 “ Aristotle contemplating a bust of Homer”, where the Greek philosopher
  Aristotle puts his hands on the head of Homer, suggesting that Aristotle will interpret
  and add to Homer’s rendition of Greek history. Aristotle, in the view taken here,
  is interested above all in shedding light on the story and not so much in Homer’s
  inner world. The film’s analyst- interpreter plays the role of Aristotle trying
  to understand more fully what Homer- the artist-creator- is expressing. In the
  view taken here, the ultimate creator of the work of art, or story, can be seen
  as society itself, and that story needs deciphering, beyond the work of the creator-artist.
</p>
<p>
  Second, this site is not, as stated elsewhere, about the aesthetic dimension
  of films. Not once, will there be comments about the aesthetic qualities or
  weaknesses of the film, the quality of its photography, or the work of its
  actors, for example. There are many sites that address these important
  dimensions, but that will not be the focus here. We of course recognize that
  there are significant links between the style and the content of a film, but
  those links will not be the focus here.
</p>
<p>
  Thirdly, there is no attempt here to analyze a film through some sort of
  explicit and pre-established formal procedure, whether semiotics or some other
  formal method.
  <a href="/en/hermeneutics">Hermeneutics</a> is essentially a general guide and
  inspiration, not a detailed technique. In our daily lives, we are all shrinks
  of sorts, we interpret all the time, searching for the small and larger
  meanings around us, and so we all are interpreters.
  <em>The Movie Shrink</em> applies this normal activity systematically to better
  understand particularly significant and complex films.
</p>
<p>
  No attempt, either, to espouse some militant or politically charged sub-text,
  conscious or not, criticizing or supporting capitalism or globalization for
  example. Such partisan approaches will not be part of our comments, at least
  not consciously, although we may touch upon those and other sensitive subjects
  in what we believe is an analytical and reflective way. There are other venues
  for overtly political analyses of cinema production and many of them are quite
  enlightening.
</p>
<p>
  After identifying some of the elements our site is not about, the reader is
  invited to go to other sections of this site.
</p>

// pages/about.vue
<template>
  <div id="about-page" class="page-wrapper about-page content-page">
    <div class="content">
      <h2>THE MOVIE SHRINK</h2>
      <h3 style="margin-left: 10px;">
        <em>- Understanding significant films</em>
      </h3>
      <p>
        <em>The Movie Shrink</em> is a cinema commentary site that focuses on
        films that have something particularly meaningful to say to us about our
        contemporary world and the societies within it.
      </p>
      <p>
        Concentrating on a few dozen carefully chosen films a year from all over
        the planet, two each month, the site begins by offering an informed
        analysis and interpretation of what these significant films tell us
        about what it is to be living in our times.
      </p>
      <p>
        The approach taken to better understand these significant films is based
        on the tradition of
        <nuxt-link to="/hermeneutics">hermeneutics</nuxt-link>.
      </p>
      <p>
        Stated broadly,
        <nuxt-link to="/hermeneutics">hermeneutics</nuxt-link> concerns the art
        and method of interpretation. It has of course many dimensions and
        applications. Its application to films is part of the larger tradition
        of applying <nuxt-link to="/hermeneutics">hermeneutics</nuxt-link> to
        artistic creations. Seen in this light, art is not only a question of
        aesthetics, but it participates in the search for knowledge. More
        specifically, in our case, knowledge about society and its many
        contemporary dimensions.
      </p>

      <h3>
        MORE ABOUT US
      </h3>
      <p>
        After viewing certain films, we often are left with some questions and
        the feeling that there was more to the story than its script told us:
        was there a lesson to be learned; what did the film director want to
        tell us, or is that relevant; or, was there no message or meaning at
        all?
      </p>
      <p>
        Sometimes we would like to share those questions and our understanding
        of the film with those of others. Alas, more often than not, our
        friends, family, or colleagues have not viewed that specific film, and
        have seen other films that we, ourselves, have not seen. Film critics
        will often judge the artistic merits of the movie, and give it a
        comparative ranking, sometimes recommending it, but that does not always
        enlighten us with a fuller understanding of the film we have seen.
      </p>
      <p>
        So, with whom should we compare notes?
      </p>
      <p>
        <em>The Movie Shrink</em> constitutes a partial but specific answer to
        these questions. It is a meeting place, a forum for initiating a
        conversation, a dialogue for the understanding of particularly
        significant and complex films of the world.
      </p>
      <p>
        All conversation or dialogue must begin with a specific statement.
        <em>The Movie Shrink</em> thus begins, in this site, with an opening
        statement on a particular film, in the form of a specific understanding
        and interpretation of the film that is under scrutiny. It gets, as it
        were, the ball rolling.
      </p>
      <p>
        Once an interpretation has been offered on this site, readers can join
        the conversation at <b>The Movie Shrink's Forum</b>, to read comments
        coming from others who have viewed that film, and eventually participate
        in the exchanges by offering an understanding or interpretations of
        their own. Of course, viewers that want to view a film from scratch,
        without being influenced by the interpretation and understanding offered
        on this site, could read our comments only after having viewed the
        movie. In our capsules analyzing specific films, there are, to this end,
        spoiler alerts to remind the reader.
      </p>
      <p>
        In offering a specific interpretation for a film, to get the ball
        rolling, as suggested earlier, we need some guidelines that are explicit
        and methodical, yet flexible enough to adapt to the understanding of the
        specific film under study. With these guidelines, we try to avoid the
        risk that our analysis, understanding, and interpretation become only
        wild speculation or a uniquely personal view of the film that has been
        viewed.
      </p>
      <p>
        And so, the next question becomes: is there a discipline, a tradition of
        sorts, that helps us navigate towards a better understanding of the film
        under scrutiny? We believe to have found such explicit yet flexible
        guidelines in the tradition of
        <nuxt-link to="/hermeneutics">hermeneutics</nuxt-link>, as suggested at
        the outset.
      </p>
      <p>
        <em>The Movie Shrink</em> proposes to begin the exchanges by using the
        <nuxt-link to="/hermeneutics">hermeneutic</nuxt-link> approach, applied
        to films, to reach a better understanding of what can be considered as
        the larger story behind the specific and more limited story in the film.
        More can be read on
        <nuxt-link to="/hermeneutics">hermeneutics</nuxt-link> by going to
        <nuxt-link to="/hermeneutics">hermeneutics</nuxt-link> on this site.
      </p>
      <p>
        The underlying assumption of this site, as stated earlier, is that art
        and films, in particular, say a lot about where we are, today, in the
        human story. They can be seen, indeed, as chapters in the human story.
      </p>
      <p>
        <nuxt-link to="/hermeneutics">Hermeneutics</nuxt-link> is involved in
        the search for understanding when a work of art (in our case, a film)
        tells us something about where we are today, collectively, but says it
        in an indirect and understated way. The object of this site is to follow
        this <nuxt-link to="/hermeneutics">hermeneutic</nuxt-link> road to
        understand films that present some intriguing and challenging elements
        which demand interpretation for a fuller understanding. The 1653
        painting of Rembrandt, “Aristotle contemplating a bust of Homer”,
        represents a visual model of what we want to achieve in this site: the
        poet (Homer or, in our case, the filmmaker) tells a story, but the
        philosopher (Aristotle or, in our case the interpreter or analyst of the
        film) offers an understanding that may go beyond the story that is told
        in the film and beyond the intentions of the creator (or the filmmaker).
      </p>
      <p>
        This site is not about the aesthetics of a film or its artistic merit.
        Again, taking Rembrandt’s painting as an example and inspiration (see
        the painting shown on this site), Aristotle is not presumed to comment
        critically on Homer’s style of writing. In keeping with this spirit, not
        once will we comment on the artistic or creative aspects of a film (its
        photography or acting for example). This is why this site is definitely
        not film criticism.
      </p>

      <h3>ABOUT JEAN-CHARLES MERCIER</h3>
      <p>
        Jean-Charles Mercier (a.k.a. Jean Mercier) is a professor of political
        science at Université Laval in Québec City, Canada, where he taught for
        several decades on politics,
        <nuxt-link to="https://en.wikipedia.org/wiki/Institutional_economics"
          >institutional economics</nuxt-link
        >, environmental policies, and interpretative methods. He started
        writing on cinema in different Canadian reviews in the 1990’s. More is
        available on his overall activities at jean-mercier.com
      </p>
      <h3>
        WHAT THIS FILM SITE IS NOT
      </h3>
      <p>
        Before going further in describing what this site,
        <em>The Movie Shrink</em>, is about, let us say a few words about what
        it is not.
      </p>
      <p>
        Although the title of our film site could suggest that we are looking at
        the artist’s psychological makeup, <em>The Movie Shrink</em> is not
        about individual psychology at all, but about collective and social
        elements that are present in specific significant films. It is not,
        consequently, about the inner-world or intention of the author,
        screenwriter, filmmaker, or director. There is indeed no search about
        the intentions of the artist, of the writer, or the creator. We are
        interested in the outcome, the film itself, and believe that the film
        has a meaning beyond its creator, as the artists are not necessarily
        conscious of the richness of their creation. We are, on the other hand,
        very much interested in the opinion of the artist or filmmaker
        concerning his creation, but we are not tied by it. In this spirit, we
        want to draw, again, the reader’s attention to Rembrandts’ painting of
        1653 “ Aristotle contemplating a bust of Homer”, where the Greek
        philosopher Aristotle puts his hands on the head of Homer, suggesting
        that Aristotle will interpret and add to Homer’s rendition of Greek
        history. Aristotle, in the view taken here, is interested above all in
        shedding light on the story and not so much in Homer’s inner world. The
        film’s analyst- interpreter plays the role of Aristotle trying to
        understand more fully what Homer- the artist-creator- is expressing. In
        the view taken here, the ultimate creator of the work of art, or story,
        can be seen as society itself, and that story needs deciphering, beyond
        the work of the creator-artist.
      </p>
      <p>
        Second, this site is not, as stated elsewhere, about the aesthetic
        dimension of films. Not once, will there be comments about the aesthetic
        qualities or weaknesses of the film, the quality of its photography, or
        the work of its actors, for example. There are many sites that address
        these important dimensions, but that will not be the focus here. We of
        course recognize that there are significant links between the style and
        the content of a film, but those links will not be the focus here.
      </p>
      <p>
        Thirdly, there is no attempt here to analyze a film through some sort of
        explicit and pre-established formal procedure, whether semiotics or some
        other formal method.
        <nuxt-link to="/hermeneutics">Hermeneutics</nuxt-link> is essentially a
        general guide and inspiration, not a detailed technique. In our daily
        lives, we are all shrinks of sorts, we interpret all the time, searching
        for the small and larger meanings around us, and so we all are
        interpreters. <em>The Movie Shrink</em> applies this normal activity
        systematically to better understand particularly significant and complex
        films.
      </p>
      <p>
        No attempt, either, to espouse some militant or politically charged
        sub-text, conscious or not, criticizing or supporting capitalism or
        globalization for example. Such partisan approaches will not be part of
        our comments, at least not consciously, although we may touch upon those
        and other sensitive subjects in what we believe is an analytical and
        reflective way. There are other venues for overtly political analyses of
        cinema production and many of them are quite enlightening.
      </p>
      <p>
        After identifying some of the elements our site is not about, the reader
        is invited to go to other sections of this site.
      </p>
    </div>
  </div>
</template>
<script>
export default {
  head() {
    return {
      title: `About | ${this.$siteConfig.siteName}`
    }
  }
}
</script>
